/can_bridge:
  ros__parameters:
    angular_accel_limit: 10.0
    arm_angle:
      antiwindup: true
      kd: 0.0429394724786192
      ki: 0.0
      kp: 0.484149678899235
      max: 0.302593620687272
      min: -0.30144099552381
      use_velocity_for_d_term: false
    arm_length:
      antiwindup: true
      kd: 0.0
      ki: 0.0
      kp: 10.0
      max: 0.8
      min: -0.8
      use_velocity_for_d_term: true
    can_id: 200
    can_interface: can0
    command_lifespan_sec: 1.0
    drive:
      antiwindup: true
      kd: 0.0
      ki: 0.0
      kp: 6.80748916804723
      max: 40.0
      min: -40.0
      use_velocity_for_d_term: false
    expander:
      antiwindup: true
      kd: 0.0
      ki: 0.0
      kp: 6.85590727940512
      max: 0.336311220780966
      min: -0.34553319617886
      use_velocity_for_d_term: true
    linear_accel_limit: 10.0
    steer:
      antiwindup: true
      kd: 0.0391262587694517
      ki: 2.25156026194287
      kp: 1.09457509859525
      max: 0.8
      min: -0.8
      use_velocity_for_d_term: false
    steer0:
      offset: -0.0
    steer1:
      offset: 0.0
    steer2:
      offset: 0.0
    steer3:
      offset: -0.0

