/can_bridge:
  ros__parameters:
    angular_accel_limit: 1000.0
    arm_angle:
      antiwindup: true
      kd: 0.0739318299931772
      ki: 0.0
      kp: 1.41622665370917
      max: 0.302593620687272
      min: -0.30144099552381
      use_velocity_for_d_term: false
    arm_length:
      antiwindup: true
      kd: 0.482477196348667
      ki: 0.0
      kp: 17.6188190110431
      max: 0.813767500188556
      min: -0.80748917028868
      use_velocity_for_d_term: false
    can_id: 200
    can_interface: can0
    command_lifespan_sec: 1.0
    drive:
      antiwindup: true
      kd: 0.0
      ki: 0.0
      kp: 6.80748916804723
      max: 40.0
      min: -40.0
      use_velocity_for_d_term: false
    expander:
      antiwindup: true
      kd: 0.0
      ki: 0.0
      kp: 6.85590727940512
      max: 0.467665952896184
      min: -0.68822269806921
      use_velocity_for_d_term: true
    linear_accel_limit: 1000.0
    lock_arm_angle: false
    steer:
      antiwindup: true
      kd: 0.0432069134086172
      ki: 0.0
      kp: 0.763322114892799
      max: 0.8
      min: -0.8
      use_velocity_for_d_term: false
    steer0:
      offset: -0.0
    steer1:
      offset: 0.0
    steer2:
      offset: 0.0
    steer3:
      offset: -0.0

