/can_bridge:
  ros__parameters:
    angular_accel_limit: 10.0
    arm_angle:
      antiwindup: true
      kd: 0.0392434988147994
      ki: 0.0
      kp: 0.695035460990283
      max: 0.152245850511699
      min: -0.14515365059814
      use_velocity_for_d_term: false
    arm_length:
      antiwindup: true
      kd: 0.264775413713356
      ki: 0.0
      kp: 10.3282521475635
      max: 0.415602820843005
      min: -0.42784018384269
      use_velocity_for_d_term: false
    can_id: 200
    can_interface: can0
    command_lifespan_sec: 1.0
    drive:
      antiwindup: true
      kd: 0.0
      ki: 0.0
      kp: 3.57919621749413
      max: 40.0
      min: -40.0
      use_velocity_for_d_term: false
    expander:
      antiwindup: true
      kd: 0.0
      ki: 0.0
      kp: 7.33618843682506
      max: 0.455791944247555
      min: -0.60827422621615
      use_velocity_for_d_term: true
    linear_accel_limit: 5.0
    lock_arm_angle: false
    steer:
      antiwindup: true
      kd: 0.0208037834224033
      ki: 0.0
      kp: 0.364066193848588
      max: 0.391962187196325
      min: -0.39078014372265
      use_velocity_for_d_term: false
    steer0:
      offset: 0.0
    steer1:
      offset: 0.0
    steer2:
      offset: 0.0
    steer3:
      offset: -0.0

