/emcl2:
  ros__parameters:
    scan_topics: [scan0, scan1]
    sensor_reset: false
    num_particles: 50
    range_threshold: 0.05
    laser_likelihood_max_dist: 0.1
    alpha_threshold: 0.975
    odom_fw_dev_per_fw: 0.01
    odom_fw_dev_per_rot: 0.01
    odom_rot_dev_per_fw: 0.01
    odom_rot_dev_per_rot: 0.01
    expansion_radius_position: 0.1
    expansion_radius_orientation: 0.1
    initial_pose_x: -0.5
    initial_pose_y: 0.5
    initial_pose_a: 0.0
