/wall_tracer:
  ros__parameters:
    angular_pid_gain:
      antiwindup: true
      kd: 0.183297644534212
      ki: 0.0
      kp: 1.87580299785615
      max: 5.0
      min: -5.0
      use_velocity_for_d_term: true
    enable_turn: false
    in_course_distance: 2.25
    line_fitting:
      inlierDistanceThreshold: 0.05
      iterationCount: 1000
      minDistanceBetweenSamples: 1.0
      minLineLength: 0.5
      stopTotalLineLength: 1.0
    lookahead_distance_incourse: 0.5
    lookahead_distance_outcourse: 0.5
    odom_lifespan: 1.0
    out_course_distance: 0.75
    parking_course_distance: 0.5
    robot_size_x: 0.7
    robot_size_y: 0.7

